services:
  - type: web
    name: gwp-app
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: DATABASE_URL=file:/opt/render/project/src/db-data/prod.db npx prisma db push --accept-data-loss && npm start
    disk:
      name: gwp-data
      mountPath: /opt/render/project/src/db-data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/opt/render/project/src/db-data/prod.db
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
