# shopify.app.toml

name = "GWP - Gift With Purchase"
client_id = "4fd28b1f0bd91b4480cfdba0459ae16e"  
application_url = "https://fuumuui-clearing.onrender.com"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_customers,read_customers,write_discounts,read_discounts,write_cart_transforms,read_cart_transforms,read_orders"

[auth]
redirect_urls = [
  "https://fuumuui-clearing.onrender.com/auth/callback",
  "https://fuumuui-clearing.onrender.com/auth/shopify/callback",
  "https://fuumuui-clearing.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[app_proxy]
url = "https://fuumuui-clearing.onrender.com/api/gwp"
subpath = "gwp"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
