api_version = "2026-01"
uid = "08e8285f-5495-5cd0-d629-8939c0104aebc99a5cc7"

[[extensions]]
name = "GWP Product Discount"
handle = "gwp-discount"
type = "function"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
  watch = ["src/**/*.js"]

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.ui]
  enable_create = false

    [extensions.ui.paths]
    create = "/app/campaign/new"
    details = "/app/campaign/:id"
